appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pgGMLCfOeSdm+BXnKy+qMQPCJFRBVHVsyYGJKNuxKwOaOc4tdJo+edCTpp4wQsyFQVYE0qYE7EzUrMIf65GRnX7m95F9MV1qKkoTl4mwRT1DthgX7oj0Z1C+qQ8ojDEK4ATSOEWczDP7E5wIqPm3U6gPBWv6LjCPj+MqUKe7E4l0NQk2qUxsgC+xD/N3sE6TGPfQqhCAhIGopbtwsnK9Hmi0K3n0JA1ufepBeRYLZrVSZZ4cN0UoZHHtgXyS18HzpcLl2AG4W2g8O5RzrtwAN8lEzeZQ+rveJaMwamUD0xRRBuErpXCiA69qdbyb2y0/7d5DuSwymcBzVADlo+nnkwhEn0TQ1qJIXV9UN4UFgafWDYRDpVcdgfvAIFP7O28JFwJZa9ebd+fFo8jWtHTDqBsJ8E7E9BjLSJXujdo209HUCJ+7Bgo/i7elv9t+CEt8jxBIHAgsvtVQ54qxRl4jZLcsRzm19ZX2V/JwUZ0ytVazL9PlBZvPpWMK/THEovJUjJHFFGeh5gQZR5UIVMvuiYLrUwrgNzb+RlMDhp7kt43ftdYXBhY4E7uSve1QjC6sqLQKScexwBivyKzX9nsaY6Y9aP+0pEOfFEjC33CA/s+oeLGrYnYriiaCMQGEIdwyKH7uDDTqvqw0ad2ffakKL/dbexOp/oeGRjZFzL7CCuI=}
